import { PrismaClient } from '../app/generated/prisma/client'
import { PrismaLibSql } from '@prisma/adapter-libsql'
import path from 'path'

const dbPath = path.resolve(process.cwd(), 'dev.db')
const adapter = new PrismaLibSql({ url: `file:${dbPath}` })
const db = new PrismaClient({ adapter })

const seed = [
  {
    id: 'pineapple-jazz-funk-1-1800',
    studioName: 'Pineapple Dance Studios',
    studioWebsite: 'https://www.pineapple.uk.com',
    bookingUrl: 'https://www.pineapple.uk.com/pages/dance-classes-for-adults-at-pineapple-dance-studios',
    className: 'Jazz Funk',
    instructor: 'Sarah Mitchell',
    genre: 'Jazz',
    level: 'All levels',
    dayOfWeek: 1,
    startTime: '18:00',
    endTime: '19:00',
    location: 'Covent Garden',
    price: '£16',
  },
  {
    id: 'pineapple-hip-hop-3-1900',
    studioName: 'Pineapple Dance Studios',
    studioWebsite: 'https://www.pineapple.uk.com',
    bookingUrl: 'https://www.pineapple.uk.com/pages/dance-classes-for-adults-at-pineapple-dance-studios',
    className: 'Hip Hop Foundations',
    instructor: 'DJ Marcus',
    genre: 'Hip-hop/Street',
    level: 'Beginner',
    dayOfWeek: 3,
    startTime: '19:00',
    endTime: '20:00',
    location: 'Covent Garden',
    price: '£16',
  },
  {
    id: 'manor-kpop-2-1800',
    studioName: 'The Manor LDN',
    studioWebsite: 'https://www.themanorldn.com',
    bookingUrl: 'https://www.themanorldn.com/timetable',
    className: 'K-Pop Class',
    instructor: 'Jess Kim',
    genre: 'K-pop/Commercial',
    level: 'All levels',
    dayOfWeek: 2,
    startTime: '18:00',
    endTime: '19:30',
    location: 'Shoreditch',
    price: '£18',
  },
  {
    id: 'manor-heels-4-2000',
    studioName: 'The Manor LDN',
    studioWebsite: 'https://www.themanorldn.com',
    bookingUrl: 'https://www.themanorldn.com/timetable',
    className: 'Heels Choreo',
    instructor: 'Rina Adeyemi',
    genre: 'Heels',
    level: 'Intermediate',
    dayOfWeek: 4,
    startTime: '20:00',
    endTime: '21:00',
    location: 'Shoreditch',
    price: '£18',
  },
  {
    id: 'base-afrobeats-5-1700',
    studioName: 'Base Dance Studios',
    studioWebsite: 'https://www.basedancestudios.com',
    bookingUrl: 'https://www.basedancestudios.com/book-your-class',
    className: 'Afrobeats Fusion',
    instructor: 'Kwame Osei',
    genre: 'Afro',
    level: 'All levels',
    dayOfWeek: 5,
    startTime: '17:00',
    endTime: '18:30',
    location: 'East London',
    price: '£15',
  },
  {
    id: 'base-contemporary-6-1100',
    studioName: 'Base Dance Studios',
    studioWebsite: 'https://www.basedancestudios.com',
    bookingUrl: 'https://www.basedancestudios.com/book-your-class',
    className: 'Contemporary Flow',
    instructor: 'Emma Clarke',
    genre: 'Ballet/Contemporary',
    level: 'Intermediate',
    dayOfWeek: 6,
    startTime: '11:00',
    endTime: '12:30',
    location: 'East London',
    price: '£15',
  },
  {
    id: 'ventures-hiphop-3-1730',
    studioName: 'Ventures Studio',
    studioWebsite: 'https://bookwhen.com/ventures-studio',
    bookingUrl: 'https://bookwhen.com/ventures-studio',
    className: 'Hip Hop Choreography - Beginners',
    instructor: 'Nevin',
    genre: 'Hip-hop/Street',
    level: 'Beginner',
    dayOfWeek: 3,
    startTime: '17:30',
    endTime: '18:30',
    location: 'North London',
    price: '£12',
  },
  {
    id: 'ventures-kpop-6-1300',
    studioName: 'Ventures Studio',
    studioWebsite: 'https://bookwhen.com/ventures-studio',
    bookingUrl: 'https://bookwhen.com/ventures-studio',
    className: "BTS '2.0' K-Pop Class",
    instructor: 'Nevin',
    genre: 'K-pop/Commercial',
    level: 'All levels',
    dayOfWeek: 6,
    startTime: '13:00',
    endTime: '14:00',
    location: 'North London',
    price: '£12',
  },
  {
    id: 'playground-heels-2-1930',
    studioName: 'Playground London',
    studioWebsite: 'https://playgroundlondon.dance',
    bookingUrl: 'https://playgroundlondon.dance/schedule',
    className: 'Heels & Femme Styles',
    instructor: 'Lucia Vega',
    genre: 'Heels',
    level: 'All levels',
    dayOfWeek: 2,
    startTime: '19:30',
    endTime: '20:45',
    location: 'South London',
    price: '£14',
  },
  {
    id: 'playground-afro-4-1800',
    studioName: 'Playground London',
    studioWebsite: 'https://playgroundlondon.dance',
    bookingUrl: 'https://playgroundlondon.dance/schedule',
    className: 'Afro Dance',
    instructor: 'Tobi Adewale',
    genre: 'Afro',
    level: 'Beginner',
    dayOfWeek: 4,
    startTime: '18:00',
    endTime: '19:15',
    location: 'South London',
    price: '£14',
  },
]

async function main() {
  console.log('Seeding database...')
  for (const cls of seed) {
    await db.danceClass.upsert({
      where: { id: cls.id },
      update: cls,
      create: { ...cls, lastScraped: new Date() },
    })
  }
  console.log(`Seeded ${seed.length} classes.`)
  await db.$disconnect()
}

main().catch(e => { console.error(e); process.exit(1) })
